name: plexsim
channels:
  - conda-forge
  - numba
  - nvidia
dependencies:
  - python=3.9.12
  - cudatoolkit=11.6.0
  - numpy=1.22.4
  - numba=0.55.2
  - cupy=10.6.0
  - h5py=3.7.0
  - pyyaml
  - tqdm
