initializer: maxwellian

environment:
  coordinate_system: cartesian
  grid_shape: [138, 138, 64]
  cell_size: [0.00925644, 0.00925644, 0.01144227]
  external_magnetic_field: ../common/B.npy
  external_electric_field: [0, 0, 0]
  field_dtype: fp64
  valid_cell_coords: ../common/valid_cell_coords.npy
  constant_field_coords: ../common/constant_field_coords.npy
  relative_permittivity: 1
  relative_permeability: 1

grids:
  -
    species: electron
    dtype:
      X: fp32
      U: fp32
    n_splits: 2
    n_computational_to_physical: 1.e+10
    initial_condition:
      temperature: ./data/Te.npy  # [eV]
      density: ./data/ne.npy  # [m^-3]
      current_density: ./data/J.npy

      tracking:
        n_particles: 20
        sample: random

  -
    species: ion
    dtype:
      X: fp32
      U: fp32
    n_splits: 2
    n_computational_to_physical: 1.e+10
    initial_condition:
      temperature: ./data/Ti.npy  # [eV]
      density: ./data/ni.npy  # [m^-3]

      tracking:
        n_particles: 20
        sample: random

simulation:
  chunk_size: 1.e+6
  iteration_encoding: file
  save_state: No
