initializer: maxwellian

environment:
  coordinate_system: cylindrical
  grid_shape: [64, 64, 10]
  cell_size: [0.07190764, 0.05594311]
  scale_length: 1.
  r0: 0.43281836
  external_magnetic_field: ./data/input-cylindrical/B_cyl.npy
  external_electric_field: [0, 0, 0]
  field_dtype: fp64
  relative_permittivity: 1
  relative_permeability: 1

grids:
  -
    species: electron
    dtype:
      X: fp64
      U: fp64
    n_splits: 2
    n_computational_to_physical: 1.e+12
    initial_condition:
      temperature: ./data/input-cylindrical/Te.npy  # [eV]
      density: ./data/input-cylindrical/ne.npy  # [m^-3]
      current_density: ./data/input-cylindrical/J.npy

      tracking:
        n_particles: 20
        sample: random

  -
    species: ion
    dtype:
      X: fp64
      U: fp64
    n_splits: 2
    n_computational_to_physical: 1.e+12
    initial_condition:
      temperature: ./data/input-cylindrical/Ti.npy  # [eV]
      density: ./data/input-cylindrical/ni.npy  # [m^-3]

      tracking:
        n_particles: 20
        sample: random

simulation:
  backend: local
  chunk_size: 1.e+6
  iteration_encoding: file
  save_state: No
